"""
Build api/sqlite/data.sql from the canonical JSON files in data/json/.

D1 has practical limits on a single SQL statement (~1MB) and on the number
of statements per execute (~10k). We chunk multi-row INSERTs into batches
of 100 to stay well below both.

Output: api/sqlite/data.sql with categories, words, senses, translations,
word-category assignments, and dataset_meta rows.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data" / "json"
OUT = ROOT / "api" / "sqlite" / "data.sql"

BATCH = 100


def lit(s) -> str:
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def batched_insert(rows: list[str], header: str) -> list[str]:
    """Return a list of complete INSERT statements, each with up to BATCH rows."""
    statements = []
    for i in range(0, len(rows), BATCH):
        chunk = rows[i : i + BATCH]
        statements.append(header + "\n" + ",\n".join(chunk) + ";\n")
    return statements


def main() -> None:
    categories = json.loads((DATA / "categories.json").read_text(encoding="utf-8"))
    words = json.loads((DATA / "words_en.json").read_text(encoding="utf-8"))
    translations = json.loads(
        (DATA / "translations_fa.json").read_text(encoding="utf-8")
    )
    word_categories = json.loads(
        (DATA / "word_categories.json").read_text(encoding="utf-8")
    )

    statements: list[str] = []

    # categories
    cat_rows = [
        f"  ('{c['id']}', {lit(c['slug'])}, {lit(c['name_en'])})" for c in categories
    ]
    statements += batched_insert(
        cat_rows,
        "INSERT OR IGNORE INTO categories (id, slug, name_en) VALUES",
    )

    # words
    word_rows = [
        f"  ('{w['id']}', {lit(w['english'])}, "
        f"{w.get('frequency_rank') if w.get('frequency_rank') is not None else 'NULL'}, "
        f"{lit(w.get('level'))}, {lit(w.get('source_list'))})"
        for w in words
    ]
    statements += batched_insert(
        word_rows,
        "INSERT OR IGNORE INTO words (id, english, frequency_rank, level, source_list) VALUES",
    )

    # senses
    sense_rows = []
    for w in words:
        for s in w["senses"]:
            sense_rows.append(
                f"  ('{s['id']}', '{w['id']}', {lit(s['part_of_speech'])}, "
                f"{s['sense_order']}, {lit(s['definition_en'])}, {lit(s.get('example_en'))})"
            )
    statements += batched_insert(
        sense_rows,
        "INSERT OR IGNORE INTO word_senses "
        "(id, word_id, part_of_speech, sense_order, definition_en, example_en) VALUES",
    )

    # translations
    trans_rows = [
        f"  ('{t['id']}', '{t['sense_id']}', {lit(t['language_code'])}, "
        f"{lit(t['meaning'])}, {lit(t.get('example'))})"
        for t in translations
    ]
    statements += batched_insert(
        trans_rows,
        "INSERT OR IGNORE INTO sense_translations "
        "(id, sense_id, language_code, meaning, example) VALUES",
    )

    # word_categories
    wc_rows = [
        f"  ('{wc['word_id']}', '{wc['category_id']}')" for wc in word_categories
    ]
    statements += batched_insert(
        wc_rows,
        "INSERT OR IGNORE INTO word_categories (word_id, category_id) VALUES",
    )

    # dataset_meta
    meta = [
        ("schema_version", "1.0.0"),
        ("dataset_version", "0.2.0"),
        ("license", "MIT"),
        ("homepage", "https://github.com/amirj4m/openjam"),
        (
            "source_attribution",
            "WordNet 3.1 (Princeton), wordfreq, AI translations (Claude)",
        ),
    ]
    meta_rows = [f"  ({lit(k)}, {lit(v)})" for k, v in meta]
    statements += batched_insert(
        meta_rows,
        "INSERT OR REPLACE INTO dataset_meta (key, value) VALUES",
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Openjam D1 data dump (auto-generated by build-data.py)\n\n")
        f.writelines(statements)

    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(categories)} categories")
    print(f"  {len(words)} words")
    print(f"  {len(sense_rows)} senses")
    print(f"  {len(translations)} translations")
    print(f"  {len(word_categories)} word-category assignments")
    print(f"  {len(statements)} SQL statements")


if __name__ == "__main__":
    main()
