-- Openjam: category taxonomy (35 categories, flat).
-- Auto-generated by scripts/generate_seed.py

BEGIN;

INSERT INTO categories (id, slug, name_en) VALUES
  ('560b4bf0-03a1-587f-9b24-ff23fced31fa', 'food', 'Food'),
  ('2e43fd71-e27f-5ef9-95e5-9c872fe463cf', 'drink', 'Drink'),
  ('09ee0872-4d02-5196-8b67-d6343e126879', 'body', 'Body parts'),
  ('eb488b51-a3fd-543d-83b6-36afa4c49450', 'clothing', 'Clothing'),
  ('0261e854-2004-5e96-9553-b73ce1dd7112', 'home', 'Home and household'),
  ('73e6f4d4-a680-513a-9995-42a96d7dabf7', 'animal', 'Animals'),
  ('e2fa8660-a128-5d31-ab9d-0bc4ab6213a0', 'plant', 'Plants'),
  ('05b9a093-6b59-5a85-8762-a2cd05f8a12a', 'nature', 'Nature and weather'),
  ('6dd4fbed-18c5-51dd-a038-e6558f14d502', 'vehicle', 'Vehicles and transport'),
  ('57381fde-1a82-56f6-8f25-330bcdf625d1', 'tool', 'Tools and devices'),
  ('63200e6a-384d-5b80-bf87-1ae5f49a44af', 'family', 'Family'),
  ('853a6480-a80d-5125-9b9a-97899648cfb9', 'person', 'People'),
  ('3f0e5d18-155d-5bd3-86a2-5edef8cdd507', 'profession', 'Professions'),
  ('0a52777f-75a0-50d3-8b76-cd1c118825db', 'relationship', 'Relationships'),
  ('f20c58e3-4541-5184-ad96-dae832d67aa2', 'emotion', 'Emotions'),
  ('1cac6386-a0ac-5ec5-9200-22848e672b42', 'society', 'Society and politics'),
  ('11c34d45-ed35-5c2d-94b1-4aa15cd731a0', 'place', 'Places'),
  ('a833ed7d-921d-58b1-831e-fd2b85599d13', 'country', 'Countries'),
  ('ca12f121-de4e-5de0-bb6b-8462441281fe', 'city', 'Cities'),
  ('0c9b12b2-e0c9-5c83-8bb1-f0fca6e96995', 'travel', 'Travel'),
  ('042febdd-f9f5-5232-b2de-b331a1f3a051', 'work', 'Work and business'),
  ('07ae9f8d-9328-5143-8a80-99ac65823186', 'school', 'School and education'),
  ('756f00fb-4dfc-5e21-989e-dd6bb96e12ec', 'sport', 'Sports and games'),
  ('51fce64e-2e07-5e1f-b2da-25f0bdf5440b', 'arts', 'Arts and culture'),
  ('f10d34c9-8ab5-5064-9b36-f1995e2916e5', 'religion', 'Religion'),
  ('a141ac4d-6b97-5c6e-90a6-51a74b83b445', 'media', 'Media and communication'),
  ('951465bc-ae65-502c-a00c-22858c073855', 'health', 'Health and medicine'),
  ('c2121f72-9c5a-537a-94fd-d403b2a11f0d', 'science', 'Science'),
  ('dd6cf916-9e70-50e8-8264-f3400ae89f95', 'technology', 'Technology'),
  ('1ff34e8f-726a-53ed-aa2c-e39fdc07519e', 'time', 'Time'),
  ('5456c91a-749d-5276-bde0-0b0435970299', 'money', 'Money and finance'),
  ('64a0b003-b32f-549b-88e3-e89409a7033b', 'quality', 'Qualities and descriptions'),
  ('40a7546e-a676-533f-bc08-cc284840d6a9', 'action', 'Actions and movement'),
  ('0b12e8c0-3137-5d32-be5a-c0d0249280cb', 'abstract', 'Abstract concepts'),
  ('a8901f99-c87d-5699-b572-6b2736a74daf', 'event', 'Events')
ON CONFLICT (slug) DO NOTHING;

COMMIT;
