-- Openjam: word <-> category assignments.
-- Auto-generated by scripts/generate_seed.py

BEGIN;

INSERT INTO word_categories (word_id, category_id) VALUES
  ('3acee99a-3b3d-58ae-8396-e5a06880108f', '40a7546e-a676-533f-bc08-cc284840d6a9'),
  ('3acee99a-3b3d-58ae-8396-e5a06880108f', '0b12e8c0-3137-5d32-be5a-c0d0249280cb'),
  ('b15f4d2c-2d23-51a2-a087-75ea389f7376', '40a7546e-a676-533f-bc08-cc284840d6a9'),
  ('b15f4d2c-2d23-51a2-a087-75ea389f7376', '0b12e8c0-3137-5d32-be5a-c0d0249280cb'),
  ('f4f87c00-04a2-5671-98fc-fa3a59b3de12', '0b12e8c0-3137-5d32-be5a-c0d0249280cb'),
  ('73a8ac62-61a9-5f7a-8f07-88e1f0cd6ec8', '0b12e8c0-3137-5d32-be5a-c0d0249280cb'),
  ('73a8ac62-61a9-5f7a-8f07-88e1f0cd6ec8', '64a0b003-b32f-549b-88e3-e89409a7033b'),
  ('310c2fa9-d556-59b0-8838-74235d45c640', '40a7546e-a676-533f-bc08-cc284840d6a9'),
  ('310c2fa9-d556-59b0-8838-74235d45c640', '042febdd-f9f5-5232-b2de-b331a1f3a051'),
  ('add8c8ab-2bb7-5b4c-b5d1-b2a3f615a128', '40a7546e-a676-533f-bc08-cc284840d6a9'),
  ('add8c8ab-2bb7-5b4c-b5d1-b2a3f615a128', '0b12e8c0-3137-5d32-be5a-c0d0249280cb'),
  ('c3a0c274-17b7-5452-95fe-e00c6ca0c94c', '0b12e8c0-3137-5d32-be5a-c0d0249280cb'),
  ('c3a0c274-17b7-5452-95fe-e00c6ca0c94c', '64a0b003-b32f-549b-88e3-e89409a7033b'),
  ('60ce3736-686c-5583-9c7c-46f43548e74b', '64a0b003-b32f-549b-88e3-e89409a7033b'),
  ('60ce3736-686c-5583-9c7c-46f43548e74b', '0b12e8c0-3137-5d32-be5a-c0d0249280cb'),
  ('29c2daec-2ba6-5ea2-96cc-68c03a775f76', '40a7546e-a676-533f-bc08-cc284840d6a9'),
  ('7a0c3f74-dd9f-5323-82d6-84a0669402b5', '1ff34e8f-726a-53ed-aa2c-e39fdc07519e'),
  ('7a0c3f74-dd9f-5323-82d6-84a0669402b5', '0b12e8c0-3137-5d32-be5a-c0d0249280cb')
ON CONFLICT (word_id, category_id) DO NOTHING;

COMMIT;
