-- Openjam: English words + senses
-- Source: wordfreq (frequency) + Princeton WordNet 3.1 (senses, definitions, examples)
-- Auto-generated by scripts/generate_seed.py

BEGIN;

INSERT INTO words (id, english, frequency_rank, level, source_list) VALUES
  ('3acee99a-3b3d-58ae-8396-e5a06880108f', 'be', 8, 'A1', 'wordfreq+wordnet'),
  ('b15f4d2c-2d23-51a2-a087-75ea389f7376', 'have', 20, 'A1', 'wordfreq+wordnet'),
  ('f4f87c00-04a2-5671-98fc-fa3a59b3de12', 'not', 23, 'A1', 'wordfreq+wordnet'),
  ('73a8ac62-61a9-5f7a-8f07-88e1f0cd6ec8', 'so', 33, 'A1', 'wordfreq+wordnet'),
  ('310c2fa9-d556-59b0-8838-74235d45c640', 'can', 39, 'A1', 'wordfreq+wordnet'),
  ('add8c8ab-2bb7-5b4c-b5d1-b2a3f615a128', 'will', 40, 'A1', 'wordfreq+wordnet'),
  ('c3a0c274-17b7-5452-95fe-e00c6ca0c94c', 'just', 41, 'A1', 'wordfreq+wordnet'),
  ('60ce3736-686c-5583-9c7c-46f43548e74b', 'more', 49, 'A1', 'wordfreq+wordnet'),
  ('29c2daec-2ba6-5ea2-96cc-68c03a775f76', 'do', 50, 'A1', 'wordfreq+wordnet'),
  ('7a0c3f74-dd9f-5323-82d6-84a0669402b5', 'time', 60, 'A1', 'wordfreq+wordnet')
ON CONFLICT (english) DO NOTHING;

INSERT INTO word_senses (id, word_id, part_of_speech, sense_order, definition_en, example_en) VALUES
  ('50f09ea8-80c9-5aeb-8abf-4c6dcc4fcd94', '3acee99a-3b3d-58ae-8396-e5a06880108f', 'verb', 1, 'have the quality of being; (copula, used with an adjective or a predicate noun)', 'John is rich'),
  ('f5df9202-64bb-53de-9cbb-514970270d9f', '3acee99a-3b3d-58ae-8396-e5a06880108f', 'verb', 2, 'be identical to; be someone or something', 'The president of the company is John Smith'),
  ('12b1b544-6b4e-5ae3-b195-6f542647175f', 'b15f4d2c-2d23-51a2-a087-75ea389f7376', 'verb', 1, 'have or possess, either in a concrete or an abstract sense', 'She has $1,000 in the bank'),
  ('65bc975b-df18-5880-b190-2bb08c5f7b5d', 'b15f4d2c-2d23-51a2-a087-75ea389f7376', 'verb', 2, 'have as a feature', 'This restaurant features the most famous chefs in France'),
  ('743adb23-bd00-52db-8b38-3d4727643300', 'f4f87c00-04a2-5671-98fc-fa3a59b3de12', 'adverb', 1, 'negation of a word or group of words', 'he does not speak French'),
  ('1e8570fa-d29c-5ee1-b5ac-fd29a6ceced5', '73a8ac62-61a9-5f7a-8f07-88e1f0cd6ec8', 'adverb', 1, 'to a very great extent or degree', 'the idea is so obvious'),
  ('5e5b8796-5ccb-576a-bfe4-cffef836cbe5', '73a8ac62-61a9-5f7a-8f07-88e1f0cd6ec8', 'adverb', 2, 'in a manner that facilitates', 'he observed the snakes so he could describe their behavior'),
  ('1f100bad-c828-53f0-8ee6-c9a08572dce8', '310c2fa9-d556-59b0-8838-74235d45c640', 'verb', 1, 'preserve in a can or tin', 'tinned foods are not very tasty'),
  ('045d908e-7f1b-512b-a2c5-653ced04fe8c', '310c2fa9-d556-59b0-8838-74235d45c640', 'verb', 2, 'terminate the employment of; discharge from an office or position', 'The boss fired his secretary today'),
  ('faffdcef-71ec-52bd-ba86-4319918a329d', 'add8c8ab-2bb7-5b4c-b5d1-b2a3f615a128', 'verb', 1, 'decree or ordain', 'God wills our existence'),
  ('c9857b5a-8fe9-568d-8a31-1b0c9623d847', 'add8c8ab-2bb7-5b4c-b5d1-b2a3f615a128', 'verb', 2, 'determine by choice', 'This action was willed and intended'),
  ('9c939a37-4075-5a15-9a50-9476734edde5', 'c3a0c274-17b7-5452-95fe-e00c6ca0c94c', 'adverb', 1, 'and nothing more', 'I was merely asking'),
  ('b8099537-779b-5411-a163-2daec8fc2971', 'c3a0c274-17b7-5452-95fe-e00c6ca0c94c', 'adverb', 2, 'indicating exactness or preciseness', 'he was doing precisely (or exactly) what she had told him to do'),
  ('8a3d6b8c-5549-5080-a08a-2d44c623b7d2', '60ce3736-686c-5583-9c7c-46f43548e74b', 'adjective', 1, '(comparative of `much'' used with mass nouns) a quantifier meaning greater in size or amount or extent or degree', 'more land'),
  ('12c79556-8547-5194-a0d1-433a056ec520', '60ce3736-686c-5583-9c7c-46f43548e74b', 'adjective', 2, '(comparative of `many'' used with count nouns) quantifier meaning greater in number', 'a hall with more seats'),
  ('5d69a005-0b63-593a-a088-8c169bd48be7', '60ce3736-686c-5583-9c7c-46f43548e74b', 'adverb', 1, 'used to form the comparative of some adjectives and adverbs', 'more interesting'),
  ('24986c6c-df1a-5c32-ac02-666ff5cee6e8', '60ce3736-686c-5583-9c7c-46f43548e74b', 'adverb', 2, 'comparative of much; to a greater degree or extent', 'he works more now'),
  ('3b89aaec-3f3b-5102-b8f4-703a9a681047', '29c2daec-2ba6-5ea2-96cc-68c03a775f76', 'verb', 1, 'engage in', 'make love, not war'),
  ('dc7b8bb9-f48d-552f-b982-76e5701e1c19', '29c2daec-2ba6-5ea2-96cc-68c03a775f76', 'verb', 2, 'carry out or perform an action', 'John did the painting, the weeding, and he cleaned out the gutters'),
  ('8a4a289b-6e15-5995-8f83-c9cb1ba9c14b', '7a0c3f74-dd9f-5323-82d6-84a0669402b5', 'noun', 1, 'an instance or single occasion for some event', 'this time he succeeded'),
  ('85b197ae-82fa-5a16-b48e-8959cc20329e', '7a0c3f74-dd9f-5323-82d6-84a0669402b5', 'noun', 2, 'a period of time considered as a resource under your control and sufficient to accomplish something', 'take time to smell the roses')
ON CONFLICT (word_id, part_of_speech, sense_order) DO NOTHING;

COMMIT;
