"""
Fill the gap in English example sentences.

About half of openjam senses came from WordNet without an example
(WordNet doesn't always include one). This script asks Claude to
generate a clean example sentence for every sense that has a
non-empty definition_en but a NULL example_en.

For efficiency it sends ONE Claude call per word, listing all the
empty senses of that word in one prompt and getting back a sentence
per sense in the same order.

Input:  data/json/words_en.json (rewritten in place)
Output: data/json/words_en.json + data/sql/words_en.sql

Idempotent: a word with no empty senses is skipped. Re-running only
re-processes words still missing examples.

Environment:
  ANTHROPIC_API_KEY  required
  OPENJAM_MODEL      optional, default claude-haiku-4-5-20251001
  N_WORDS            optional cap, useful for smoke tests
"""

from __future__ import annotations

import json
import os
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHECKPOINT_EVERY = 50


def load_env_file() -> None:
    env_path = ROOT / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and not os.environ.get(key):
            os.environ[key] = value


def extract_json(text: str) -> str:
    import re
    text = text.strip()
    if text.startswith("```"):
        body = text.split("```", 2)
        if len(body) >= 2:
            inner = body[1]
            if inner.startswith("json"):
                inner = inner[4:]
            text = inner.strip()
            if text.endswith("```"):
                text = text[:-3].strip()
    first = min((p for p in (text.find("{"), text.find("[")) if p != -1), default=-1)
    if first > 0:
        text = text[first:]
    last = max(text.rfind("}"), text.rfind("]"))
    if last != -1 and last < len(text) - 1:
        text = text[: last + 1]
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    text = text.replace("“", '"').replace("”", '"').replace("‘", "'").replace("’", "'")
    return text


def ask_for_examples(client, model: str, english: str, missing_senses: list[dict]) -> list[str]:
    """Return one example sentence per sense, in the same order as input."""
    lines = "\n".join(
        f"{i + 1}. ({s['part_of_speech']}) {s['definition_en']}"
        for i, s in enumerate(missing_senses)
    )
    prompt = f"""Write one short, natural English example sentence for each sense of "{english}" below.

Senses:
{lines}

Rules:
- 6-15 words per sentence.
- Sentence must clearly demonstrate this exact sense (not another meaning of the word).
- The target word "{english}" (or its inflected form) MUST appear in the sentence.
- Common, present-day usage. No archaic or overly formal language.
- No quotation marks around the sentence.

Return ONLY a JSON array of sentences in the same order, nothing else:
["sentence for sense 1", "sentence for sense 2", ...]
"""
    msg = client.messages.create(
        model=model,
        max_tokens=1500,
        messages=[{"role": "user", "content": prompt}],
    )
    parsed = json.loads(extract_json(msg.content[0].text))
    if not isinstance(parsed, list):
        raise ValueError(f"expected JSON array, got {type(parsed).__name__}")
    return [str(s).strip() for s in parsed]


def sql_literal(s) -> str:
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def write_words_sql(path: Path, words: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Openjam: English words + senses\n")
        f.write("-- Source: wordfreq (frequency) + Princeton WordNet 3.1 (senses)\n")
        f.write("-- Auto-generated by scripts/generate_seed.py + scripts/fill_english_examples.py\n\n")
        f.write("BEGIN;\n\n")
        f.write("INSERT INTO words (id, english, frequency_rank, level, source_list) VALUES\n")
        rows = [
            "  ('{id}', {english}, {rank}, {level}, {source})".format(
                id=w["id"],
                english=sql_literal(w["english"]),
                rank=w["frequency_rank"] if w["frequency_rank"] is not None else "NULL",
                level=sql_literal(w["level"]),
                source=sql_literal(w["source_list"]),
            )
            for w in words
        ]
        f.write(",\n".join(rows))
        f.write("\nON CONFLICT (english) DO NOTHING;\n\n")
        f.write("INSERT INTO word_senses (id, word_id, part_of_speech, sense_order, definition_en, example_en) VALUES\n")
        sense_rows = []
        for w in words:
            for s in w["senses"]:
                sense_rows.append(
                    "  ('{id}', '{word_id}', {pos}, {order}, {definition}, {example})".format(
                        id=s["id"],
                        word_id=w["id"],
                        pos=sql_literal(s["part_of_speech"]),
                        order=s["sense_order"],
                        definition=sql_literal(s["definition_en"]),
                        example=sql_literal(s["example_en"]),
                    )
                )
        f.write(",\n".join(sense_rows))
        f.write("\nON CONFLICT (word_id, part_of_speech, sense_order) DO NOTHING;\n\n")
        f.write("COMMIT;\n")


def main() -> int:
    load_env_file()
    model = os.environ.get("OPENJAM_MODEL", "claude-haiku-4-5-20251001")
    cap = int(os.environ.get("N_WORDS", "999999"))

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
        return 1

    words_path = ROOT / "data/json/words_en.json"
    words = json.loads(words_path.read_text(encoding="utf-8"))

    # Identify words that need at least one example filled.
    to_process: list[dict] = []
    for w in words:
        empty = [s for s in w["senses"] if not s.get("example_en")]
        if empty:
            to_process.append(w)
    if cap < len(to_process):
        to_process = to_process[:cap]

    total_empty_senses = sum(
        1 for w in to_process for s in w["senses"] if not s.get("example_en")
    )
    print(f"[1/3] {len(words)} total words")
    print(f"      {len(to_process)} words have at least one empty example_en")
    print(f"      {total_empty_senses} total senses need a sentence")

    if not to_process:
        print("Nothing to do.")
        return 0

    import anthropic
    client = anthropic.Anthropic()

    max_workers = int(os.environ.get("FILL_WORKERS", "8"))
    print(f"[2/3] Filling examples via {model} ({max_workers} parallel workers)")

    # Build a quick lookup so we can mutate senses in-place.
    sense_by_id = {s["id"]: s for w in words for s in w["senses"]}

    filled_senses = 0
    failures: list[tuple[str, str]] = []
    completed = 0
    lock = threading.Lock()
    start = time.time()

    def process_word(w: dict) -> tuple[dict, list[dict], list[str] | None, str | None]:
        empty = [s for s in w["senses"] if not s.get("example_en")]
        try:
            sentences = ask_for_examples(client, model, w["english"], empty)
        except Exception as exc:
            return w, empty, None, str(exc)
        return w, empty, sentences, None

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(process_word, w): w for w in to_process}
        for fut in as_completed(futures):
            w, empty, sentences, err = fut.result()
            with lock:
                completed += 1
                if err:
                    failures.append((w["english"], err))
                else:
                    for sense, sent in zip(empty, sentences):
                        if not sent or not isinstance(sent, str):
                            continue
                        sense_by_id[sense["id"]]["example_en"] = sent
                        filled_senses += 1
                if completed % CHECKPOINT_EVERY == 0 or completed == len(to_process):
                    words_path.write_text(
                        json.dumps(words, ensure_ascii=False, indent=2),
                        encoding="utf-8",
                    )
                    elapsed = time.time() - start
                    remaining = len(to_process) - completed
                    eta = (elapsed / completed) * remaining if completed else 0
                    print(
                        f"      [{completed}/{len(to_process)}] "
                        f"+{filled_senses} senses {w['english']:<20s} "
                        f"elapsed={elapsed:5.0f}s eta={eta:5.0f}s",
                        flush=True,
                    )

    # Final write.
    words_path.write_text(json.dumps(words, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"[3/3] Writing SQL")
    write_words_sql(ROOT / "data/sql/words_en.sql", words)
    print("      -> rewrote data/sql/words_en.sql")

    # Coverage report so the user knows the exact final state.
    total_senses = sum(len(w["senses"]) for w in words)
    senses_with_example = sum(
        1 for w in words for s in w["senses"] if s.get("example_en")
    )
    words_with_any = sum(
        1 for w in words if any(s.get("example_en") for s in w["senses"])
    )
    print()
    print(f"DONE: filled {filled_senses} new example sentences")
    print()
    print(f"Coverage after this run:")
    print(f"  senses with example_en: {senses_with_example}/{total_senses} "
          f"({senses_with_example * 100 // total_senses}%)")
    print(f"  words with at least one: {words_with_any}/{len(words)} "
          f"({words_with_any * 100 // len(words)}%)")
    if failures:
        print(f"FAILURES: {len(failures)} words failed (re-run to retry):")
        for w, err in failures[:10]:
            print(f"  - {w}: {err}")
        if len(failures) > 10:
            print(f"  ... and {len(failures) - 10} more")
    return 0


if __name__ == "__main__":
    sys.exit(main())
