"""
Openjam IPA + word forms generator.

For each English lemma in data/json/words_en.json:
  - IPA pronunciation via eng_to_ipa (CMU dict-based, MIT-compatible).
    Stored as the `ipa` field on the existing 'us' phonetics row.
  - All inflected forms via lemminflect (MIT-licensed).
    Each (form, word_id, form_type) is stored as a row in word_forms.

Outputs (overwrites existing phonetics.json, creates word_forms.json):
  data/json/phonetics.json
  data/json/word_forms.json
  data/sql/word_phonetics.sql   (rewritten with IPA filled in)
  data/sql/word_forms.sql

Idempotent: re-running with the same words gives the same output.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import eng_to_ipa as ipa
from lemminflect import getAllInflections

ROOT = Path(__file__).resolve().parent.parent

# Map our Openjam part_of_speech enum to lemminflect's UPOS tags.
POS_TO_UPOS = {
    "noun": "NOUN",
    "verb": "VERB",
    "adjective": "ADJ",
    "adverb": "ADV",
}

# Penn Treebank tag -> human-readable form_type label.
TAG_TO_TYPE = {
    # verbs
    "VB": "base",
    "VBD": "past",
    "VBG": "gerund",
    "VBN": "past_participle",
    "VBP": "non_3rd_present",
    "VBZ": "3rd_present",
    # nouns
    "NN": "singular",
    "NNS": "plural",
    "NNP": "proper",
    "NNPS": "proper_plural",
    # adjectives
    "JJ": "base",
    "JJR": "comparative",
    "JJS": "superlative",
    # adverbs
    "RB": "base",
    "RBR": "comparative",
    "RBS": "superlative",
}

PUBLIC_BASE_URL = "https://audio.openjam.amirj4m.com"


def sql_str(s) -> str:
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def safe_ipa(word: str) -> str | None:
    """Convert a word to IPA. Returns None if eng_to_ipa can't resolve it.

    eng_to_ipa returns "word*" (with trailing star) when the word isn't in
    the CMU dictionary; treat those as unresolved.
    """
    try:
        out = ipa.convert(word)
    except Exception:
        return None
    out = out.strip()
    if not out or out.endswith("*") or out == word:
        return None
    return out


def generate_forms(word: str, pos: str) -> set[tuple[str, str]]:
    """Returns set of (surface_form, form_type) for a lemma at a given POS."""
    upos = POS_TO_UPOS.get(pos)
    if not upos:
        return set()
    forms: set[tuple[str, str]] = set()
    try:
        inflections = getAllInflections(word, upos=upos)
    except Exception:
        return set()
    for tag, surfaces in (inflections or {}).items():
        ftype = TAG_TO_TYPE.get(tag, tag.lower())
        for surface in surfaces:
            s = surface.lower().strip()
            if s and s != word:  # don't store the lemma itself as a "form"
                forms.add((s, ftype))
    return forms


def write_phonetics_sql(path: Path, phonetics: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Openjam: word phonetics (IPA + audio URLs)\n")
        f.write("-- Auto-generated by scripts/generate_ipa_and_forms.py\n\n")
        f.write("BEGIN;\n\n")
        if not phonetics:
            f.write("-- (no phonetics)\n")
            f.write("COMMIT;\n")
            return
        f.write(
            "INSERT INTO word_phonetics (word_id, variant, ipa, audio_url) VALUES\n"
        )
        rows = [
            "  ('{wid}', '{var}', {ipa}, {url})".format(
                wid=p["word_id"],
                var=p["variant"],
                ipa=sql_str(p.get("ipa")),
                url=sql_str(p.get("audio_url")),
            )
            for p in phonetics
        ]
        f.write(",\n".join(rows))
        f.write(
            "\nON CONFLICT (word_id, variant) DO UPDATE SET "
            "ipa = excluded.ipa, audio_url = excluded.audio_url;\n\n"
        )
        f.write("COMMIT;\n")


def write_word_forms_sql(path: Path, forms: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Openjam: inflected word forms mapped back to lemmas\n")
        f.write("-- Auto-generated by scripts/generate_ipa_and_forms.py\n\n")
        f.write("BEGIN;\n\n")
        if not forms:
            f.write("-- (no forms)\n")
            f.write("COMMIT;\n")
            return
        f.write("INSERT INTO word_forms (form, word_id, form_type) VALUES\n")
        rows = [
            "  ({form}, '{wid}', {ftype})".format(
                form=sql_str(f_["form"]),
                wid=f_["word_id"],
                ftype=sql_str(f_.get("form_type")),
            )
            for f_ in forms
        ]
        f.write(",\n".join(rows))
        f.write("\nON CONFLICT (form, word_id) DO NOTHING;\n\n")
        f.write("COMMIT;\n")


def main() -> int:
    words_path = ROOT / "data" / "json" / "words_en.json"
    phonetics_path = ROOT / "data" / "json" / "phonetics.json"
    forms_path = ROOT / "data" / "json" / "word_forms.json"

    words = json.loads(words_path.read_text(encoding="utf-8"))
    print(f"[1/4] Loaded {len(words)} words")

    # Load existing phonetics (we already have audio URLs from generate_audio.py).
    existing_phonetics: dict[str, dict] = {}
    if phonetics_path.exists():
        for p in json.loads(phonetics_path.read_text(encoding="utf-8")):
            existing_phonetics[f"{p['word_id']}|{p['variant']}"] = p
    print(f"      {len(existing_phonetics)} existing phonetics rows")

    # --- IPA pass ---
    print(f"[2/4] Generating IPA for {len(words)} words")
    ipa_filled = 0
    ipa_failed = 0
    for w in words:
        key = f"{w['id']}|us"
        ipa_str = safe_ipa(w["english"])
        if ipa_str:
            ipa_filled += 1
        else:
            ipa_failed += 1

        record = existing_phonetics.get(key, {
            "word_id": w["id"],
            "variant": "us",
            "ipa": None,
            "audio_url": f"{PUBLIC_BASE_URL}/us/{w['english']}.mp3",
        })
        record["ipa"] = ipa_str
        existing_phonetics[key] = record
    print(f"      IPA resolved: {ipa_filled}, missing: {ipa_failed}")

    phonetics = list(existing_phonetics.values())
    phonetics_path.write_text(
        json.dumps(phonetics, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # --- Inflections pass ---
    print(f"[3/4] Generating word forms (inflections)")
    all_forms: list[dict] = []
    seen: set[tuple[str, str]] = set()
    for w in words:
        # Each word has senses with different POS; collect inflections per POS,
        # de-duplicate (form, word_id) since multiple senses may share a form.
        pos_set = {s["part_of_speech"] for s in w["senses"]}
        for pos in pos_set:
            for surface, ftype in generate_forms(w["english"], pos):
                key = (surface, w["id"])
                if key in seen:
                    continue
                seen.add(key)
                all_forms.append({
                    "form": surface,
                    "word_id": w["id"],
                    "form_type": ftype,
                })
    print(f"      {len(all_forms)} inflected forms generated")

    forms_path.write_text(
        json.dumps(all_forms, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # --- SQL output ---
    print(f"[4/4] Writing SQL")
    write_phonetics_sql(ROOT / "data" / "sql" / "word_phonetics.sql", phonetics)
    write_word_forms_sql(ROOT / "data" / "sql" / "word_forms.sql", all_forms)
    print("      -> data/sql/word_phonetics.sql  (with IPA filled)")
    print("      -> data/sql/word_forms.sql")

    print()
    print(f"DONE: IPA for {ipa_filled}/{len(words)} words, "
          f"{len(all_forms)} word_forms rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
