"""
Openjam audio generator.

Pipeline:
  1. Read data/json/words_en.json.
  2. For each word, generate an MP3 via Amazon Polly (Neural voice).
  3. Stream-upload the MP3 to Cloudflare R2 bucket `openjam-audio`.
  4. Record the public audio URL in data/json/phonetics.json.
  5. Emit data/sql/word_phonetics.sql with the (word_id, variant, audio_url) rows.

Resumable: existing phonetics in data/json/phonetics.json are reused,
so re-running only generates audio for words missing the chosen variant.

Environment:
  AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION  -- Polly
  R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_ENDPOINT   -- R2 upload
  VOICE_VARIANT   optional, default 'us' (or 'uk')
  N_WORDS         optional cap, useful for smoke tests
"""

from __future__ import annotations

import json
import os
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (Polly voice, BCP-47 language) for each accent variant we support.
VOICE_BY_VARIANT: dict[str, dict[str, str]] = {
    "us": {"voice": "Joanna", "language": "en-US"},
    "uk": {"voice": "Amy", "language": "en-GB"},
}

CHECKPOINT_EVERY = 50
PUBLIC_BASE_URL = "https://audio.openjam.amirj4m.com"
R2_BUCKET = "openjam-audio"


def load_env_file() -> None:
    env_path = ROOT / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and not os.environ.get(key):
            os.environ[key] = value


def sql_str(s) -> str:
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def write_phonetics_sql(path: Path, phonetics: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Openjam: word phonetics with audio URLs\n")
        f.write("-- Auto-generated by scripts/generate_audio.py\n\n")
        f.write("BEGIN;\n\n")
        if not phonetics:
            f.write("-- (no phonetics yet)\n")
            f.write("COMMIT;\n")
            return
        f.write(
            "INSERT INTO word_phonetics (word_id, variant, ipa, audio_url) VALUES\n"
        )
        rows = [
            "  ('{wid}', '{var}', {ipa}, {url})".format(
                wid=p["word_id"],
                var=p["variant"],
                ipa=sql_str(p.get("ipa")),
                url=sql_str(p["audio_url"]),
            )
            for p in phonetics
        ]
        f.write(",\n".join(rows))
        f.write(
            "\nON CONFLICT (word_id, variant) DO UPDATE SET audio_url = excluded.audio_url;\n\n"
        )
        f.write("COMMIT;\n")


def main() -> int:
    load_env_file()

    variant = os.environ.get("VOICE_VARIANT", "us").lower()
    if variant not in VOICE_BY_VARIANT:
        print(
            f"ERROR: VOICE_VARIANT must be one of {list(VOICE_BY_VARIANT)}",
            file=sys.stderr,
        )
        return 1
    cfg = VOICE_BY_VARIANT[variant]
    n_words = int(os.environ.get("N_WORDS", "999999"))

    for required in (
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
        "AWS_REGION",
        "R2_ACCESS_KEY_ID",
        "R2_SECRET_ACCESS_KEY",
        "R2_ENDPOINT",
    ):
        if not os.environ.get(required):
            print(f"ERROR: {required} is not set", file=sys.stderr)
            return 2

    import boto3

    polly = boto3.client(
        "polly",
        region_name=os.environ["AWS_REGION"],
        aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
    )
    r2 = boto3.client(
        "s3",
        endpoint_url=os.environ["R2_ENDPOINT"],
        aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
        region_name="auto",
    )

    words_path = ROOT / "data" / "json" / "words_en.json"
    words = json.loads(words_path.read_text(encoding="utf-8"))
    if n_words < len(words):
        words = words[:n_words]

    phonetics_path = ROOT / "data" / "json" / "phonetics.json"
    existing: dict[str, dict] = {}
    if phonetics_path.exists():
        for p in json.loads(phonetics_path.read_text(encoding="utf-8")):
            existing[f"{p['word_id']}|{p['variant']}"] = p
    phonetics = list(existing.values())

    print(
        f"[1/2] Audio generation: voice={cfg['voice']} ({variant}), "
        f"{len(words)} words, {len(existing)} existing phonetics",
        flush=True,
    )

    pending = [w for w in words if f"{w['id']}|{variant}" not in existing]
    skipped = len(words) - len(pending)
    print(f"      pending: {len(pending)} (skipping {skipped} already done)", flush=True)

    start = time.time()
    failures: list[tuple[str, str]] = []
    lock = threading.Lock()
    new_count = 0

    def process_one(w: dict) -> tuple[str, dict | None, str | None]:
        word = w["english"]
        try:
            resp = polly.synthesize_speech(
                Text=word,
                OutputFormat="mp3",
                VoiceId=cfg["voice"],
                Engine="neural",
                LanguageCode=cfg["language"],
            )
            mp3 = resp["AudioStream"].read()
        except Exception as e:
            return word, None, f"polly: {e}"

        r2_key = f"{variant}/{word}.mp3"
        try:
            r2.put_object(
                Bucket=R2_BUCKET,
                Key=r2_key,
                Body=mp3,
                ContentType="audio/mpeg",
                CacheControl="public, max-age=31536000, immutable",
            )
        except Exception as e:
            return word, None, f"r2: {e}"

        return word, {
            "word_id": w["id"],
            "variant": variant,
            "ipa": None,
            "audio_url": f"{PUBLIC_BASE_URL}/{r2_key}",
        }, None

    # 8 workers keep Polly + R2 saturated without hitting TPS limits.
    # boto3 clients are thread-safe so we share a single polly/r2 instance.
    max_workers = int(os.environ.get("AUDIO_WORKERS", "8"))
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(process_one, w): w for w in pending}
        for fut in as_completed(futures):
            word, record, err = fut.result()
            with lock:
                if err:
                    failures.append((word, err))
                    continue
                phonetics.append(record)
                new_count += 1
                if new_count % CHECKPOINT_EVERY == 0:
                    phonetics_path.parent.mkdir(parents=True, exist_ok=True)
                    phonetics_path.write_text(
                        json.dumps(phonetics, ensure_ascii=False, indent=2),
                        encoding="utf-8",
                    )
                    elapsed = time.time() - start
                    remaining = len(pending) - new_count
                    eta = (elapsed / new_count) * remaining
                    print(
                        f"      [{new_count}/{len(pending)}] "
                        f"{word:<20s} elapsed={elapsed:5.0f}s eta={eta:5.0f}s",
                        flush=True,
                    )

    phonetics_path.parent.mkdir(parents=True, exist_ok=True)
    phonetics_path.write_text(
        json.dumps(phonetics, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(f"[2/2] Writing SQL")
    write_phonetics_sql(ROOT / "data" / "sql" / "word_phonetics.sql", phonetics)
    print(f"      -> wrote data/sql/word_phonetics.sql")

    print()
    print(f"DONE: {new_count} new audio files, {skipped} reused, {len(phonetics)} total")
    if failures:
        print(f"FAILURES: {len(failures)}:")
        for word, err in failures[:10]:
            print(f"  - {word}: {err}")
        if len(failures) > 10:
            print(f"  ... and {len(failures) - 10} more")
    return 0


if __name__ == "__main__":
    sys.exit(main())
