"""
Build the books layer's SQL and JSON outputs from books/<slug>/ inputs
and the current openjam core dataset.

Reads:
  books/<slug>/meta.json
  books/<slug>/words.json
  data/json/words_en.json    (for openjam word_id lookups)

Writes:
  data/sql/book_lists.sql           INSERTs into book_lists
  data/sql/book_list_words.sql      INSERTs into book_list_words
  books/<slug>/built.json           per-book denormalised payload (optional)

Words present in the book but not yet in openjam are recorded with
word_id = NULL — they will resolve after a later run of
scripts/books/extend_openjam.py.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def sql_str(s) -> str:
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def write_book_lists_sql(path: Path, books: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Openjam books: vocabulary list metadata (optional layer).\n")
        f.write("-- Auto-generated by scripts/books/build_books.py\n\n")
        f.write("BEGIN;\n\n")
        f.write(
            "INSERT INTO book_lists "
            "(slug, name_en, name_fa, description, source_attribution, "
            "word_count, has_groups, group_label, group_label_fa) VALUES\n"
        )
        rows = []
        for b in books:
            has_groups = "TRUE" if b.get("has_groups") else "FALSE"
            rows.append(
                f"  ({sql_str(b['slug'])}, {sql_str(b['name_en'])}, "
                f"{sql_str(b.get('name_fa'))}, {sql_str(b.get('description'))}, "
                f"{sql_str(b.get('source_attribution'))}, {b['word_count']}, "
                f"{has_groups}, {sql_str(b.get('group_label'))}, "
                f"{sql_str(b.get('group_label_fa'))})"
            )
        f.write(",\n".join(rows))
        f.write(
            "\nON CONFLICT (slug) DO UPDATE SET "
            "name_en = excluded.name_en, name_fa = excluded.name_fa, "
            "description = excluded.description, "
            "source_attribution = excluded.source_attribution, "
            "word_count = excluded.word_count, "
            "has_groups = excluded.has_groups, "
            "group_label = excluded.group_label, "
            "group_label_fa = excluded.group_label_fa;\n\n"
        )
        f.write("COMMIT;\n")


def write_book_list_words_sql(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Openjam books: word memberships per book (optional layer).\n")
        f.write("-- Auto-generated by scripts/books/build_books.py\n\n")
        f.write("BEGIN;\n\n")
        if not rows:
            f.write("-- (no rows)\n")
            f.write("COMMIT;\n")
            return
        f.write(
            "INSERT INTO book_list_words "
            "(book_slug, english, word_id, group_name, sort_order) VALUES\n"
        )
        sql_rows = []
        for r in rows:
            wid = (
                f"'{r['word_id']}'" if r.get("word_id") else "NULL"
            )
            sql_rows.append(
                f"  ({sql_str(r['book_slug'])}, {sql_str(r['english'])}, "
                f"{wid}, {sql_str(r.get('group_name'))}, "
                f"{r.get('sort_order') if r.get('sort_order') is not None else 'NULL'})"
            )
        f.write(",\n".join(sql_rows))
        f.write("\nON CONFLICT (book_slug, english) DO UPDATE SET "
                "word_id = excluded.word_id, "
                "group_name = excluded.group_name, "
                "sort_order = excluded.sort_order;\n\n")
        f.write("COMMIT;\n")


def main() -> int:
    books_dir = ROOT / "books"
    if not books_dir.exists():
        print("ERROR: books/ directory not found", file=sys.stderr)
        return 1

    # Build english -> word_id map from the current core dataset.
    words = json.loads((ROOT / "data/json/words_en.json").read_text(encoding="utf-8"))
    eng_to_id = {w["english"]: w["id"] for w in words}
    print(f"[1/3] openjam main has {len(eng_to_id)} words available for reference")

    # Collect every book in the books/ directory.
    book_metas: list[dict] = []
    list_words_rows: list[dict] = []
    missing_per_book: dict[str, int] = {}

    for book_dir in sorted(books_dir.iterdir()):
        if not book_dir.is_dir():
            continue
        meta_file = book_dir / "meta.json"
        words_file = book_dir / "words.json"
        if not (meta_file.exists() and words_file.exists()):
            continue
        meta = json.loads(meta_file.read_text(encoding="utf-8"))
        wpayload = json.loads(words_file.read_text(encoding="utf-8"))

        book_words = wpayload.get("words", [])
        meta["word_count"] = len(book_words)
        book_metas.append(meta)

        missing = 0
        for w in book_words:
            eng = w["english"]
            wid = eng_to_id.get(eng)
            if wid is None:
                missing += 1
            list_words_rows.append({
                "book_slug": meta["slug"],
                "english": eng,
                "word_id": wid,
                "group_name": w.get("group"),
                "sort_order": w.get("order"),
            })
        missing_per_book[meta["slug"]] = missing

    print(f"[2/3] {len(book_metas)} books, {len(list_words_rows)} word memberships")
    for slug, miss in missing_per_book.items():
        if miss:
            print(f"      WARN: {slug} has {miss} words not yet in openjam core")

    write_book_lists_sql(ROOT / "data/sql/book_lists.sql", book_metas)
    write_book_list_words_sql(ROOT / "data/sql/book_list_words.sql", list_words_rows)
    print("[3/3] wrote data/sql/book_lists.sql + book_list_words.sql")

    return 0


if __name__ == "__main__":
    sys.exit(main())
